apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container
  namespace: kube-system
spec:
  serviceAccountName: fluent-bit
  volumes:
    - name: log-file
      emptyDir: {}
  terminationGracePeriodSeconds: 10
  containers:
    - image: abdelmounaimazz/fortune-logs
      name: fortune-quotes
      volumeMounts:
        - name: log-file
          mountPath: /var/logs
    - name: sidecar-container
      image: busybox
      command:
        ["sh", "-c", "while true; do cat /var/log/quotes.log; sleep 30; done"]
      volumeMounts:
        - name: log-file
          mountPath: /var/log/
